# Generated by Django 4.1.3 on 2022-11-29 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_purchasedproduct_remove_orderproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'brand')},
        ),
    ]
