# Generated by Django 4.1.3 on 2022-11-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_product_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique product with a particular brand',
        ),
    ]
