# Generated by Django 4.1.3 on 2022-11-29 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_product_unique product with a particular brand'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('brand', 'name')},
        ),
    ]
