# Generated by Django 4.1.3 on 2023-07-06 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0012_alter_purchasedproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brand',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shop',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
